#!/bin/bash

# Run kernel build within a virgin Debian container.

set -o errexit
set -o pipefail
set -o nounset

if [[ $EUID -ne 0 ]]
then
    >&2 echo "Error: This script must be run as root."
    exit 1
fi

if [[ $# -ne 1 ]]
then
    >&2 echo "Error: This script expects one parameter:"
    >&2 echo "       build-kernel-compulab_v8 GIT_TAG"
    exit 1
fi

MACHINE=compulab_v8
GIT_TAG="${1}"

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "${SCRIPTDIR}/../.."

DEBIAN_FRONTEND=noninteractive apt-get update > /dev/null
DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends -y install git ca-certificates build-essential crossbuild-essential-arm64 bc kmod cpio flex cpio libncurses5-dev bison libssl-dev wget lzop rsync debhelper fakeroot

mkdir -p "${GIT_TAG}"
cd "${GIT_TAG}"
git clone -b "${GIT_TAG}" --depth 1 https://github.com/compulab-yokneam/linux-compulab.git
cd linux-compulab

make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- ${MACHINE}_defconfig compulab.config
make -j "$(nproc)" KBUILD_IMAGE=arch/arm64/boot/Image ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- deb-pkg

BUILD_OUTPUT="${SCRIPTDIR}/../../build-output"
mkdir -p "${BUILD_OUTPUT}"
find ../ -maxdepth 1 -type f | xargs -I {} cp {} "${BUILD_OUTPUT}"

echo "========"
echo "Success!"
echo "========"
