#!/bin/bash

# Run kernel build within a virgin Debian container.

set -o errexit
set -o pipefail
set -o nounset

if [[ $EUID -ne 0 ]]
then
    >&2 echo "Error: This script must be run as root."
    exit 1
fi

if [[ $# -ne 2 ]]
then
    >&2 echo "Error: This script expects two parameters:"
    >&2 echo "       build-kernel-var-som-mx8m-nano KERNEL_BRANCH GIT_COMMIT"
    exit 1
fi

KERNEL_BRANCH="${1}"
GIT_COMMIT="${2}"

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "${SCRIPTDIR}/../.."

export DEBIAN_FRONTEND=noninteractive
apt-get update > /dev/null
apt-get --no-install-recommends -y install git ca-certificates build-essential crossbuild-essential-arm64 bc kmod cpio flex cpio libncurses5-dev bison libssl-dev wget lzop rsync debhelper fakeroot

mkdir -p "${KERNEL_BRANCH}"
cd "${KERNEL_BRANCH}"

git clone --branch "${KERNEL_BRANCH}" --single-branch https://github.com/varigit/linux-imx.git
cd linux-imx
git checkout "${GIT_COMMIT}"
git config user.email "lueschem@gmail.com"
git config user.name "Matthias Luescher"
git am "${SCRIPTDIR}"/../patches/var-som-mx8m-nano/*.patch
export ARCH=arm64
export CROSS_COMPILE=aarch64-linux-gnu-
make imx8_var_defconfig
make -j "$(nproc)" KBUILD_IMAGE=arch/arm64/boot/Image deb-pkg

BUILD_OUTPUT="${SCRIPTDIR}/../../build-output"
mkdir -p "${BUILD_OUTPUT}"
find ../ -maxdepth 1 -type f | xargs -I {} cp {} "${BUILD_OUTPUT}"

echo "========"
echo "Success!"
echo "========"
