#!/bin/bash

# Upload a Debian kernel package located in the build-output directory to PackageCloud

# Usage: upload-package-packagecloud REPOSITORY_USER REPOSITORY_NAME DISTRIBUTION DISTRIBUTION_RELEASE
# Example: upload-package-packagecloud get-edi debian debian buster

set -o nounset
set -o errexit
set -o pipefail

REPOSITORY_USER=$1
REPOSITORY_NAME=$2
DISTRIBUTION=$3
DISTRIBUTION_RELEASE=$4

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKDIR="${SCRIPTDIR}/../../build-output"

if [[ $EUID -eq 0 ]]
then
    >&2 echo "Error: This script must not be run as root."
    exit 1
fi

cd "${WORKDIR}"

sudo gem install package_cloud

PACKAGE=$(find . -name "linux-image*.deb" -and -not -name "linux-image*-dbg*.deb")
PACKAGE_DSC=$(find . -name "linux-*.dsc")

push_package()
{
    UPLOAD_PATH="${REPOSITORY_USER}/${REPOSITORY_NAME}/${DISTRIBUTION}/${DISTRIBUTION_RELEASE}"
    echo "Deploying package ${PACKAGE} and ${PACKAGE_DSC} to ${UPLOAD_PATH}."
    package_cloud push "${UPLOAD_PATH}" "${PACKAGE}"
    package_cloud push "${UPLOAD_PATH}" "${PACKAGE_DSC}"
}

push_package
