name: Build kernel for Raspberry Pi
on:
  workflow_dispatch:
    inputs:
      distribution_release:
        description: 'Debian distribution release'
        required: true
        default: 'bookworm'
      git_tag:
        description: 'Git tag of kernel (e.g. stable_20231123)'
        required: true
      kernel_defconfig:
        description: 'Kernel defconfig (e.g. bcm2711_defconfig or bcm2712_defconfig)'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull docker container
        run: docker pull debian:"${{ inputs.distribution_release }}"
      - name: Run build job within docker container
        run: docker run -v $(pwd):/data/runner debian:"${{ inputs.distribution_release }}" bash -c "/data/runner/.github/scripts/build-kernel-rpi ${{ inputs.git_tag }} ${{ inputs.kernel_defconfig }}"
      - name: Upload package to packagecloud repository
        run: ./.github/scripts/upload-kernel-packages-packagecloud "${PACKAGECLOUD_USER}" "${PACKAGECLOUD_REPOSITORY}" debian "${{ inputs.distribution_release }}"
        env:
          PACKAGECLOUD_USER: ${{ secrets.PACKAGECLOUD_USER }}
          PACKAGECLOUD_REPOSITORY: ${{ secrets.PACKAGECLOUD_REPOSITORY }}
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
